export const bscPools = [
  {
    id: 'bifi-maxi',
    logo: 'single-assets/BIFI.png',
    name: 'BIFI Maxi',
    token: 'BIFI',
    tokenDescription: 'Beefy.Finance',
    tokenAddress: '0xCa3F508B8e4Dd382eE878A314789373D80A5190A',
    tokenDecimals: 18,
    earnedToken: 'mooBIFI',
    earnedTokenAddress: '0xf7069e41C57EcC5F122093811d8c75bdB5f7c14e',
    earnContractAddress: '0xf7069e41C57EcC5F122093811d8c75bdB5f7c14e',
    pricePerFullShare: 1,
    tvl: 0,
    oracle: 'tokens',
    oracleId: 'BIFI',
    oraclePrice: 0,
    depositsPaused: false,
    status: 'active',
    platform: 'Beefy.Finance',
    assets: ['BIFI'],
    risks: [
      'COMPLEXITY_LOW',
      'BATTLE_TESTED',
      'IL_NONE',
      'MCAP_MEDIUM',
      'AUDIT',
      'CONTRACTS_VERIFIED',
    ],
    stratType: 'SingleStake',
    withdrawalFee: '0.05%',
    buyTokenUrl: 'https://app.1inch.io/#/56/swap/BNB/BIFI',
  },

  {
    id: 'lemon-lemon-busd',
    logo: 'uncategorized/epsRENBTC.png',
    name: 'Lemonswap Space',
    token: 'LEMON',
    tokenDescription: 'Lemonswap.Space',
    tokenAddress: '0x2a435Ecb3fcC0E316492Dc1cdd62d0F189be5640',
    tokenDecimals: 18,
    tokenDescriptionUrl: '#',
    earnedToken: 'MooEllipsisRenBTC',
    earnedTokenAddress: '0x24AE9e5424575690aCab61a384B6A76d69F4f89c',
    earnContractAddress: '0x24AE9e5424575690aCab61a384B6A76d69F4f89c',
    pricePerFullShare: 1,
    tvl: 0,
    oracle: 'lps',
    oracleId: 'ellipsis-renbtc',
    oraclePrice: 0,
    depositsPaused: false,
    status: 'active',
    platform: 'Ellipsis',
    assets: ['renBTC', 'BTCB'],
    risks: [
      'COMPLEXITY_LOW',
      'BATTLE_TESTED',
      'IL_NONE',
      'MCAP_LARGE',
      'AUDIT',
      'CONTRACTS_VERIFIED',
    ],
    stratType: 'StratLP',
    addLiquidityUrl: 'https://ellipsis.finance/pool/btceps',
  },
];
